# Generated by Django 4.1 on 2023-10-27 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255, null=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("GITHUB", "GITHUB"), ("GITLAB", "GITLAB")],
                        default="GITHUB",
                        max_length=255,
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, null=True)),
                ("company", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserAccount",
            },
        ),
        migrations.CreateModel(
            name="UserConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                    ),
                ),
                ("commit_interval", models.IntegerField()),
                ("max_lines", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "UserConfiguration",
            },
        ),
        migrations.CreateModel(
            name="GitHubAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.useraccount",),
        ),
    ]
