# Generated by Django 4.1 on 2023-10-22 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_id', models.CharField(max_length=255)),
                ('access_token', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('account_type', models.CharField(choices=[('GitHub', 'github'), ('GitLab', 'gitlab')], default='GitHub', max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'UserAccount',
            },
        ),
        migrations.CreateModel(
            name='GitHubAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.useraccount',),
        ),
    ]
