# Generated by Django 4.1 on 2023-10-22 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userconfiguration",
            old_name="commitsnum",
            new_name="commit_interval",
        ),
        migrations.RenameField(
            model_name="userconfiguration",
            old_name="linesnum",
            new_name="max_lines",
        ),
    ]
