# Generated by Django 4.1 on 2023-11-06 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repo_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "Repository",
            },
        ),
    ]
