# Generated by Django 4.1 on 2023-10-22 21:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0002_rename_commitsnum_userconfiguration_commit_interval_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userconfiguration",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userconfiguration",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="userconfiguration",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
