# Generated by Django 4.1 on 2023-11-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="user_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Pull_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                        to_field="user_name",
                    ),
                ),
            ],
            options={
                "db_table": "Pull_details",
            },
        ),
    ]
