# Generated by Django 4.1 on 2023-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_useraccount_user_name_pull_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashBoardFetch",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("account.pull_details",),
        ),
        migrations.AddField(
            model_name="pull_details",
            name="pull_id",
            field=models.IntegerField(default=None, max_length=255),
        ),
    ]
