# Generated by Django 4.1 on 2023-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('commitsnum', models.IntegerField()),
                ('linesnum', models.IntegerField()),
            ],
            options={
                'db_table': 'UserConfiguration',
            },
        ),
    ]
