# Generated by Django 4.1 on 2023-11-06 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_pull_details_branch_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pull_details",
            old_name="branch_name",
            new_name="Repo_name",
        ),
    ]
