# Generated by Django 4.1 on 2023-11-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_branch_branch_id_targetconfiguration_and_more'),
        ('account', '0010_rename_branch_name_pull_details_repo_name'),
    ]

    operations = [
    ]
