stages:
  - test
  - deploy

backend-test:
  image: python:3.11.4-bullseye
  stage: test
  before_script:
    - python3 -m pip install poetry
    - python3 -m poetry install
    - source $(poetry env info --path)/bin/activate
    - cat ${ENVIRONMENT_CONFIG} >> .env
  script:
    - python3 manage.py check
    - python3 manage.py test
    - echo "Test Successful!!"
  tags:
    - python-build

frontend-test:
  image: node:19-bullseye
  stage: test
  before_script:
    - cd static/refactor-ui
    - yarn install
  script:
    - yarn build
    - echo "Build Successful!!"
  tags:
    - react-build
