default:
  image: ubuntu:20.04
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.11 python3-pip
    - apt -y upgrade
    - pip install poetry
    - poetry install
    - poetry shell


migrations:
  stage: build
  script:
    - python3 manage.py check
  tags:
    - group10-runner


django-tests:
  stage: test
  script:
    - python3 manage.py test
  tags:
    - group10-runner

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
  tags:
    - group10-runner
