default:
  image: ubuntu:20.04
  before_script:
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.11.4 python3-pip mysql-client=="2.1.1" libmysqlclient-dev poetry
    - apt -y upgrade
    - poetry install
    - poetry shell


migrations:
  stage: build
  script:
    - python3 manage.py check


django-tests:
  stage: test
  script:
    - python3 manage.py test

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
