default:
  image: python:3.11.6-bullseye
  before_script:
    - python3 -m pip install poetry
    - python3 -m poetry install
    - python3 -m poetry shell
  tags:
    - group10-runner


migrations:
  stage: build
  script:
    - python3 manage.py check
  tags:
    - group10-runner


django-tests:
  stage: test
  script:
    - python3 manage.py test
  tags:
    - group10-runner

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
  tags:
    - group10-runner
